config/routes.rb
Myapp::Application.routes.draw do
  use_doorkeeper
  resources :reports
  devise_for :users
  require 'sidekiq/web'
  get "home/index"
  resources :keywords do
    collection { post :import }
  end

root to: 'home#index'
authenticate :user do
  mount Sidekiq::Web, at: "/sidekiq"
end
api :version => 1 do
  resources :key_words, :only => [:index, :show] do
    member { get :link}
    collection { get :links}
  end
end

end

app/models/keyword.rb
class Keyword < ActiveRecord::Base
  include RocketPants::Cacheable
  require 'nokogiri'
  require 'open-uri'
  require 'csv'

  STATES = %w(new completed wrong)  

  has_many :links

  scope :new_records, -> { where(state: %w(new)) }

  def self.import(file)
    worker_starter = true if Keyword.new_records.blank?
    CSV.foreach(file.path, headers: false) do |row|
      Keyword.create(phrase: row.first.squish.tr(" ", "+")) 
      # It removes all whitespace on both ends of the string, 
      # and then changing remaining consecutive whitespace groups 
      # into one space each and replace with + for multi words searches
      # Hope it will enough to get right search url for G :)
    end
    KeywordsWorker.perform_async #if worker_starter
  end

  STATES.each do |state|
    define_method("#{state}?") do
      self.state == state
    end
  end
end

app/models/link.rb
class Link < ActiveRecord::Base

  TYPES = %w(ads_top ads_bottom ads_right regular broken)

  self.inheritance_column = :_type_disabled

  scope :ads_top_list, -> { where(type: %w(ads_top)) }
  scope :ads_bottom_list, -> { where(type: %w(ads_bottom)) }
  scope :ads_right_list, -> { where(type: %w(ads_right)) }
  scope :search_list, -> { where(type: %w(regular)) }

  belongs_to :keyword

  after_create :update_urls

  TYPES.each do |type|
    define_method("#{type}?") do
      self.type == type
    end
  end

  private

  def update_urls
    # Cut off Google url magick :) and trying to get a real url of the link
    url = self.url[/(((ftp|https?):\/\/)(www\.)?|www\.)([\da-z-_\.]+)([a-z\.]{2,7})([\/\w\.-]*)*\/?/]
    self.update_attributes(url: url)
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/api_controller.rb
class ApiController < RocketPants::Base

  version 1

  # The list of keywords is paginated for 5 minutes, the food itself is cached
  # until it's modified (using Efficient Validation)
  caches :index, :show, :cache_for => 5.minutes

  def index
    expose Keyword.all#paginate(:page => params[:page])
  end

  def show
    expose Keyword.find(params[:id])
  end

end

app/controllers/application_controller.rb
# -*- encoding : utf-8 -*-
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/home_controller.rb
# -*- encoding : utf-8 -*-
class HomeController < ApplicationController

  before_action :authenticate_user!
  
  def index
  end

 end

app/controllers/key_words_controller.rb
class KeyWordsController < RocketPants::Base

  version 1

  # The list of keywords is paginated for 5 minutes, the keyword itself is cached
  # until it's modified (using Efficient Validation)
  caches :index, :show, :cache_for => 5.minutes

  def index
    expose Keyword.all.paginate(page: params[:page], per_page: 5)
  end

  def show
    expose Keyword.find(params[:id])
  end

  def link
    expose Link.find(params[:id])
  end

  def links
    expose Link.all.paginate(page: params[:page], per_page: 5)
  end

end

app/controllers/keywords_controller.rb
# -*- encoding : utf-8 -*-
class KeywordsController < ApplicationController

  before_action :authenticate_user!

  def import
    Keyword.import(params[:file])
    redirect_to root_url, notice: "Links imported."
  end

end

app/controllers/reports_controller.rb
class ReportsController < ApplicationController
  def index
    @keywords = Keyword.order(phrase: :asc)
  end

  def show
    @keyword = Keyword.find(params['id'])
  end
end

app/helpers/application_helper.rb
# -*- encoding : utf-8 -*-
module ApplicationHelper
  def bootstrap_class_for flash_type
    { success: "alert-success", error: "alert-danger", alert: "alert-warning", notice: "alert-info" }[flash_type.to_sym] || flash_type.to_s
  end
 
  def flash_messages(opts = {})
    flash.each do |msg_type, message|
      concat(content_tag(:div, message, class: "alert #{bootstrap_class_for(msg_type)} fade in") do 
              concat content_tag(:button, 'x', class: "close", data: { dismiss: 'alert' })
              concat message 
            end)
    end
    nil
  end
end

app/helpers/home_helper.rb
# -*- encoding : utf-8 -*-
module HomeHelper
end

app/helpers/reports_helper.rb
module ReportsHelper
end

app/views/home/index.html.erb
<center>
  <h3>Import Links from CSV file</h3>
  <p id='import_csv'>
  <%= form_tag import_keywords_path, multipart: true do %>
    <%= file_field_tag :file %>
    <br>
    <%= submit_tag "Import", class: "btn btn-primary" %>
  <% end %>
  <p>
</center>

app/views/layouts/_footer.html.erb
<footer class="">
  <small>
    2015. Test task for Alexey Brovikov. 
    <a href="https://bitbucket.org/alexeybrovikov/scraper">Sources on Bitbacket</a>
  </small>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-default">
  <div class="navbar-inner">
    <div class="container">
      <%= link_to "ScraperApp", '#', class: "navbar-brand" %>
      <nav>
        <ul class="nav navbar-nav">
          <li><%= link_to "Home",    '/' %></li>
          <% if signed_in? %>
            <li><%= link_to "Reports", reports_path %></li>
            <li><%= link_to "Sidekiq", sidekiq_web_path %></li>
            <li><%= link_to "Sign out", destroy_user_session_path, method: "delete" %></li>
          <% else %>
            <li><%= link_to "Sign in", new_user_session_path %></li>
          <% end %>
        </ul>
      </nav>
    </div>
  </div>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Test application. Alexey Brovikov</title>
    <%= stylesheet_link_tag "application", media: "all",
                                           "data-turbolinks-track" => true %>
    <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
    <%= csrf_meta_tags %>
  </head>
  <body>
    <%= render 'layouts/header' %>
    <div class="container">
       <%= flash_messages %>
      <%= yield %>
    </div>
    <%= render 'layouts/footer' %>
  </body>
</html>

app/views/reports/index.html.erb
<center>
  <h3>List of uploaded keywords</h3>

  <table class="table" data-toggle="table"  data-height="299">
    <thead>
      <tr>
        <th>Keyword</th>
        <th>Ads in Top</th>
        <th>Ads in Bottom</th>
        <th>Ads in Right</th>
        <th>Total Ads links</th>
        <th>Search links</th>
        <th>Total on page</th>
        <th>Overall total</th>
      </tr>
    </thead>
    <tbody>
      <% @keywords.each do |keyword| %>
        <tr>
          <td><%= link_to keyword.phrase, report_path(keyword) %></td>
          <td><%= keyword.ads_top_total %></td>
          <td><%= keyword.ads_bottom_total %></td>
          <td><%= keyword.ads_right_total %></td>
          <td><%= keyword.ads_total %></td>
          <td><%= keyword.search_on_page_total %></td>
          <td><%= keyword.total_links %></td>          
          <td><%= keyword.overall_total_search_res %></td>
        </tr>
       <% end %>
      </tbody>
</table>
</center>

app/views/reports/show.html.erb
<center>
  <h3>Report for keyword <b><%= @keyword.phrase %></b></h3>
  <p>
    <small>
      Total links on page: <b><%= @keyword.total_links %></b> | 
      Total AdSense links: <b><%= @keyword.ads_total %></b> |
      Overall total links: <b><%= @keyword.overall_total_search_res %></b> 
    </small>
  </p>
</center>

<div class="container">
  <div class="row">
    <div class="col-md-6">
      <p class="ads">
        <b> Top AdSense links (<%= @keyword.ads_top_total %>)</b><br>
        <% @keyword.links.ads_top_list.each do |ads| %>
        <%= link_to ads.url, ads.url %> <br>
        <% end %>
        <% if @keyword.links.ads_top_list.blank? %>
          Sorry, no one link for this category has been scrapped 
        <% end %>
      </p>

      <p class="search">
        <b> Search results (<%= @keyword.search_on_page_total %>)</b><br>
        <% @keyword.links.search_list.each do |search| %>
        <%= link_to search.url, search.url %> <br>
        <% end %>
        <% if @keyword.links.search_list.blank? %>
          Sorry, no one link for this category has been scrapped 
        <% end %>
      </p>

      <p class="ads">
        <b> Bottom AdSense links (<%= @keyword.ads_bottom_total %>) </b><br>
        <% @keyword.links.ads_bottom_list.each do |ads| %>
        <%= link_to ads.url, ads.url %> <br>
        <% end %>
        <% if @keyword.links.ads_bottom_list.blank? %>
          Sorry, no one link for this category has been scrapped 
        <% end %>
      </p>
     </div>
      <div class="col-md-6">
        <p class="ads">
          <b> Right AdSense links (<%= @keyword.ads_right_total %>)</b><br>
          <% @keyword.links.ads_right_list.each do |ads| %>
          <%= link_to ads.url, ads.url %> <br>
          <% end %>
          <% if @keyword.links.ads_right_list.blank? %>
            Sorry, no one link for this category has been scrapped 
          <% end %>
        </p>
      </div>
    </div>
</div>
<br>
<%= link_to 'Back', reports_path %>